steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run-script', 'pkg']
artifacts:
  objects:
    location: 'gs://artifacts.gcd-jr-demo.appspot.com/'
    paths: ['bin/server-linux']
